name: Experiment
on:
  workflow_call:

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out project
        uses: actions/checkout@v2

      # Configure Java
      - uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: "11"
          cache: 'maven'

      - name: Configure Git
        run: |
          git config user.name "Netty Project Bot"
          git config user.email "netty-project-bot@users.noreply.github.com"

      - name: Inspect Project (with Maven computed version)
        run: |
          mvn release:update-versions -DautoVersionSubmodules=true
          echo "inputs_version=$(mvn help:evaluate -Dexpression=project.artifactId -q -DforceStdout | sed s/-SNAPSHOT//)" >> $GITHUB_ENV
          git restore **/pom.xml
